import { productImages } from './product-images'
import type { Product } from './types'

/**
 * Mock product catalogue.
 *
 * This is intentionally small and factual — a few compliant products per
 * category so the catalogue, filters and product pages render. Pack shots live
 * under `public/products/` (see `product-images.ts` and the download script).
 * Replace with a real API by setting VITE_API_BASE_URL (see api.ts).
 *
 * COMPLIANCE NOTES (enforced here and in the UI):
 *  - Copy is plain and factual. No promotional language, no "best", no
 *    discounts, no health claims.
 *  - `compliance.singleUseDisposable` is typed `false`: single-use disposables
 *    are excluded from the catalogue by design.
 *  - `compliance.mhraNotified` reflects MHRA/TPD notification status.
 *  - Prices are stored in integer pence and include UK VAT.
 */
export const PRODUCTS: Product[] = [
  // ---------------------------------------------------------------- pod kits
  // Genuinely refillable pod systems (user adds their own e-liquid). Reusable
  // prefilled-pod devices live in the 'prefilled-pods' category. Single-use
  // disposables are never stocked (compliance.singleUseDisposable is `false`).
  {
    id: 'pk-001',
    slug: 'vaporesso-xros-5-pod-kit',
    name: 'Vaporesso XROS 5 Pod Kit',
    brand: 'Vaporesso',
    category: 'pod-kits',
    deviceType: 'pod-system',
    priceIncVatPence: 1499,
    currency: 'GBP',
    inStock: true,
    stockQty: 46,
    shortDescription: 'Refillable MTL pod kit with a 1000mAh battery and adjustable airflow.',
    description:
      'A refillable pod system with a 1000mAh integrated battery, USB-C charging and a 2ml top-fill refillable pod. Adjustable airflow and mesh coils suit mouth-to-lung vaping with nicotine salts and 50/50 e-liquids.',
    specs: [
      { label: 'Battery', value: '1000mAh integrated' },
      { label: 'Charging', value: 'USB-C' },
      { label: 'Pod capacity', value: '2ml refillable' },
      { label: 'Airflow', value: 'Adjustable' },
      { label: 'Recommended e-liquid', value: 'Nic salt or 50/50' },
    ],
    images: productImages('vaporesso-xros-5-pod-kit', 'Vaporesso XROS 5 Pod Kit'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: false },
  },
  {
    id: 'pk-002',
    slug: 'oxva-xlim-pro-2-pod-kit',
    name: 'OXVA Xlim Pro 2 Pod Kit',
    brand: 'OXVA',
    category: 'pod-kits',
    deviceType: 'pod-system',
    priceIncVatPence: 1899,
    currency: 'GBP',
    inStock: true,
    stockQty: 28,
    shortDescription: 'Refillable pod kit with adjustable power and airflow.',
    description:
      'A refillable pod system with a 1000mAh battery, USB-C charging and a 2ml refillable pod. Adjustable wattage and airflow allow tuning for mouth-to-lung or restricted direct-lung vaping with a range of e-liquids.',
    specs: [
      { label: 'Battery', value: '1000mAh integrated' },
      { label: 'Charging', value: 'USB-C' },
      { label: 'Pod capacity', value: '2ml refillable' },
      { label: 'Output', value: 'Adjustable' },
      { label: 'Airflow', value: 'Adjustable' },
    ],
    images: productImages('oxva-xlim-pro-2-pod-kit', 'OXVA Xlim Pro 2 Pod Kit'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: false },
  },
  {
    id: 'pk-003',
    slug: 'uwell-caliburn-g3-pod-kit',
    name: 'Uwell Caliburn G3 Pod Kit',
    brand: 'Uwell',
    category: 'pod-kits',
    deviceType: 'pod-system',
    priceIncVatPence: 1799,
    currency: 'GBP',
    inStock: true,
    stockQty: 22,
    shortDescription: 'Refillable MTL pod kit with a 900mAh battery and adjustable airflow.',
    description:
      'A refillable pod system with a 900mAh integrated battery, USB-C charging and a 2.5ml refillable pod. Adjustable airflow and replaceable coils suit mouth-to-lung vaping with nicotine salts and 50/50 e-liquids.',
    specs: [
      { label: 'Battery', value: '900mAh integrated' },
      { label: 'Charging', value: 'USB-C' },
      { label: 'Pod capacity', value: '2.5ml refillable' },
      { label: 'Airflow', value: 'Adjustable' },
    ],
    images: productImages('uwell-caliburn-g3-pod-kit', 'Uwell Caliburn G3 Pod Kit'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: false },
  },
  {
    id: 'pk-004',
    slug: 'aspire-flexus-q-pod-kit',
    name: 'Aspire Flexus Q Pod Kit',
    brand: 'Aspire',
    category: 'pod-kits',
    deviceType: 'pod-system',
    priceIncVatPence: 999,
    currency: 'GBP',
    inStock: true,
    stockQty: 35,
    shortDescription: 'Compact draw-activated refillable pod kit.',
    description:
      'A compact, draw-activated refillable pod system with a 700mAh integrated battery, USB-C charging and a 2ml refillable pod. Suited to mouth-to-lung vaping with nicotine salts and 50/50 e-liquids.',
    specs: [
      { label: 'Battery', value: '700mAh integrated' },
      { label: 'Charging', value: 'USB-C' },
      { label: 'Pod capacity', value: '2ml refillable' },
      { label: 'Activation', value: 'Draw-activated' },
    ],
    images: productImages('aspire-flexus-q-pod-kit', 'Aspire Flexus Q Pod Kit'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: false },
  },
  {
    id: 'pk-005',
    slug: 'vaporesso-xros-4-mini-pod-kit',
    name: 'Vaporesso XROS 4 Mini Pod Kit',
    brand: 'Vaporesso',
    category: 'pod-kits',
    deviceType: 'pod-system',
    priceIncVatPence: 1299,
    currency: 'GBP',
    inStock: true,
    stockQty: 41,
    shortDescription: 'Compact refillable pod kit with a 1000mAh battery and adjustable airflow.',
    description:
      'A compact refillable pod system with a 1000mAh integrated battery, USB-C charging and a 2ml refillable pod. Adjustable airflow suits mouth-to-lung vaping with nicotine salts and 50/50 e-liquids.',
    specs: [
      { label: 'Battery', value: '1000mAh integrated' },
      { label: 'Charging', value: 'USB-C' },
      { label: 'Pod capacity', value: '2ml refillable' },
      { label: 'Airflow', value: 'Adjustable' },
    ],
    images: productImages('vaporesso-xros-4-mini-pod-kit', 'Vaporesso XROS 4 Mini Pod Kit'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: false },
  },
  {
    id: 'pk-006',
    slug: 'oxva-xlim-se-2-pod-kit',
    name: 'OXVA Xlim SE 2 Pod Kit',
    brand: 'OXVA',
    category: 'pod-kits',
    deviceType: 'pod-system',
    priceIncVatPence: 1699,
    currency: 'GBP',
    inStock: true,
    stockQty: 31,
    shortDescription: 'Refillable pod kit with a 1200mAh battery and side airflow control.',
    description:
      'A refillable pod system with a 1200mAh integrated battery, USB-C charging and a 2ml refillable pod. Side airflow adjustment and mesh coils suit mouth-to-lung vaping with nicotine salts and 50/50 e-liquids.',
    specs: [
      { label: 'Battery', value: '1200mAh integrated' },
      { label: 'Charging', value: 'USB-C' },
      { label: 'Pod capacity', value: '2ml refillable' },
      { label: 'Airflow', value: 'Side adjustable' },
    ],
    images: productImages('oxva-xlim-se-2-pod-kit', 'OXVA Xlim SE 2 Pod Kit'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: false },
  },

  // ----------------------------------------------------------- prefilled pods
  // Reusable, rechargeable devices that take replaceable PREFILLED (closed)
  // pods. Not user-refillable, but not single-use disposables either — the
  // device is kept and recharged; only the prefilled pod is replaced.
  {
    id: 'pp-001',
    slug: 'ivg-pro-rainbow-burst-vape-kit',
    name: 'IVG Pro Rainbow Burst Vape Kit',
    brand: 'IVG',
    category: 'prefilled-pods',
    deviceType: 'pod-system',
    flavourFamily: 'fruit',
    nicotineStrengthMg: 20,
    vgPg: { vg: 50, pg: 50 },
    volumeMl: 12,
    prefilled: true,
    puffRating: 10000,
    priceIncVatPence: 1095,
    currency: 'GBP',
    inStock: true,
    stockQty: 60,
    shortDescription: 'Reusable device with a 12ml prefilled pod. Sweet mixed-fruit flavour.',
    description:
      'A reusable, rechargeable pod device supplied with a 12ml prefilled pod in a sweet mixed-fruit flavour with tangy notes. The device has a 1000mAh battery, a display and USB-C charging; the pod is replaceable but not refillable. Each prefilled pod lasts up to 10,000 puffs (manufacturer estimate).',
    specs: [
      { label: 'Device', value: 'Reusable, rechargeable' },
      { label: 'Battery', value: '1000mAh with display' },
      { label: 'Charging', value: 'USB-C' },
      { label: 'Pod', value: '12ml prefilled (replaceable, not refillable)' },
      { label: 'Pod life', value: 'Up to 10,000 puffs (manufacturer estimate)' },
      { label: 'Nicotine', value: '20mg/ml nic salt' },
    ],
    images: productImages('ivg-pro-rainbow-burst-vape-kit', 'IVG Pro Rainbow Burst Vape Kit'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: true },
  },
  {
    id: 'pp-002',
    slug: 'ivg-pro-blue-raspberry-ice-vape-kit',
    name: 'IVG Pro Blue Raspberry Ice Vape Kit',
    brand: 'IVG',
    category: 'prefilled-pods',
    deviceType: 'pod-system',
    flavourFamily: 'fruit',
    nicotineStrengthMg: 20,
    vgPg: { vg: 50, pg: 50 },
    volumeMl: 12,
    prefilled: true,
    puffRating: 10000,
    priceIncVatPence: 1095,
    currency: 'GBP',
    inStock: true,
    stockQty: 48,
    shortDescription: 'Reusable device with a 12ml prefilled pod. Blue raspberry with menthol.',
    description:
      'A reusable, rechargeable pod device supplied with a 12ml prefilled pod in a blue raspberry flavour with a menthol finish. 1000mAh battery with a display and USB-C charging; the pod is replaceable but not refillable. Each prefilled pod lasts up to 10,000 puffs (manufacturer estimate).',
    specs: [
      { label: 'Device', value: 'Reusable, rechargeable' },
      { label: 'Battery', value: '1000mAh with display' },
      { label: 'Charging', value: 'USB-C' },
      { label: 'Pod', value: '12ml prefilled (replaceable, not refillable)' },
      { label: 'Pod life', value: 'Up to 10,000 puffs (manufacturer estimate)' },
      { label: 'Nicotine', value: '20mg/ml nic salt' },
    ],
    images: productImages('ivg-pro-blue-raspberry-ice-vape-kit', 'IVG Pro Blue Raspberry Ice Vape Kit'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: true },
  },
  {
    id: 'pp-003',
    slug: 'ivg-pro-fresh-mint-vape-kit',
    name: 'IVG Pro Fresh Mint Vape Kit',
    brand: 'IVG',
    category: 'prefilled-pods',
    deviceType: 'pod-system',
    flavourFamily: 'mint',
    nicotineStrengthMg: 20,
    vgPg: { vg: 50, pg: 50 },
    volumeMl: 12,
    prefilled: true,
    puffRating: 10000,
    priceIncVatPence: 1095,
    currency: 'GBP',
    inStock: true,
    stockQty: 37,
    shortDescription: 'Reusable device with a 12ml prefilled pod. Cooling mint flavour.',
    description:
      'A reusable, rechargeable pod device supplied with a 12ml prefilled pod in a cooling mint flavour. 1000mAh battery with a display and USB-C charging; the pod is replaceable but not refillable. Each prefilled pod lasts up to 10,000 puffs (manufacturer estimate).',
    specs: [
      { label: 'Device', value: 'Reusable, rechargeable' },
      { label: 'Battery', value: '1000mAh with display' },
      { label: 'Charging', value: 'USB-C' },
      { label: 'Pod', value: '12ml prefilled (replaceable, not refillable)' },
      { label: 'Pod life', value: 'Up to 10,000 puffs (manufacturer estimate)' },
      { label: 'Nicotine', value: '20mg/ml nic salt' },
    ],
    images: productImages('ivg-pro-fresh-mint-vape-kit', 'IVG Pro Fresh Mint Vape Kit'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: true },
  },
  {
    id: 'pp-004',
    slug: 'ivg-pro-lemon-lime-vape-kit',
    name: 'IVG Pro Lemon Lime Vape Kit',
    brand: 'IVG',
    category: 'prefilled-pods',
    deviceType: 'pod-system',
    flavourFamily: 'fruit',
    nicotineStrengthMg: 20,
    vgPg: { vg: 50, pg: 50 },
    volumeMl: 12,
    prefilled: true,
    puffRating: 10000,
    priceIncVatPence: 1095,
    currency: 'GBP',
    inStock: true,
    stockQty: 44,
    shortDescription: 'Reusable device with a 12ml prefilled pod. Citrus lemon and lime flavour.',
    description:
      'A reusable, rechargeable pod device supplied with a 12ml prefilled pod in a lemon and lime flavour. 1000mAh battery with a display and USB-C charging; the pod is replaceable but not refillable. Each prefilled pod lasts up to 10,000 puffs (manufacturer estimate).',
    specs: [
      { label: 'Device', value: 'Reusable, rechargeable' },
      { label: 'Battery', value: '1000mAh with display' },
      { label: 'Charging', value: 'USB-C' },
      { label: 'Pod', value: '12ml prefilled (replaceable, not refillable)' },
      { label: 'Pod life', value: 'Up to 10,000 puffs (manufacturer estimate)' },
      { label: 'Nicotine', value: '20mg/ml nic salt' },
    ],
    images: productImages('ivg-pro-lemon-lime-vape-kit', 'IVG Pro Lemon Lime Vape Kit'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: true },
  },
  {
    id: 'pp-005',
    slug: 'ivg-pro-strawberry-watermelon-vape-kit',
    name: 'IVG Pro Strawberry Watermelon Vape Kit',
    brand: 'IVG',
    category: 'prefilled-pods',
    deviceType: 'pod-system',
    flavourFamily: 'fruit',
    nicotineStrengthMg: 20,
    vgPg: { vg: 50, pg: 50 },
    volumeMl: 12,
    prefilled: true,
    puffRating: 10000,
    priceIncVatPence: 1095,
    currency: 'GBP',
    inStock: true,
    stockQty: 52,
    shortDescription: 'Reusable device with a 12ml prefilled pod. Strawberry and watermelon flavour.',
    description:
      'A reusable, rechargeable pod device supplied with a 12ml prefilled pod in a strawberry and watermelon flavour. 1000mAh battery with a display and USB-C charging; the pod is replaceable but not refillable. Each prefilled pod lasts up to 10,000 puffs (manufacturer estimate).',
    specs: [
      { label: 'Device', value: 'Reusable, rechargeable' },
      { label: 'Battery', value: '1000mAh with display' },
      { label: 'Charging', value: 'USB-C' },
      { label: 'Pod', value: '12ml prefilled (replaceable, not refillable)' },
      { label: 'Pod life', value: 'Up to 10,000 puffs (manufacturer estimate)' },
      { label: 'Nicotine', value: '20mg/ml nic salt' },
    ],
    images: productImages(
      'ivg-pro-strawberry-watermelon-vape-kit',
      'IVG Pro Strawberry Watermelon Vape Kit',
    ),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: true },
  },

  // -------------------------------------------------------------- e-liquids
  {
    id: 'el-001',
    slug: 'strawberry-nic-salt-10ml',
    name: 'Strawberry Nic Salt 10ml',
    brand: 'Drift',
    category: 'e-liquids',
    deviceType: 'not-applicable',
    flavourFamily: 'fruit',
    nicotineStrengthMg: 10,
    vgPg: { vg: 50, pg: 50 },
    volumeMl: 10,
    priceIncVatPence: 399,
    currency: 'GBP',
    inStock: true,
    stockQty: 120,
    shortDescription: 'Sweet strawberry nicotine salt e-liquid in a 10ml bottle.',
    description:
      'A sweet strawberry nicotine salt e-liquid with a 50/50 VG/PG ratio, suited to pod systems and vape pens. Supplied in a 10ml child-resistant, tamper-evident bottle.',
    specs: [
      { label: 'Volume', value: '10ml' },
      { label: 'Nicotine', value: '10mg/ml nic salt' },
      { label: 'VG/PG', value: '50/50' },
      { label: 'Flavour', value: 'Strawberry' },
    ],
    images: productImages('strawberry-nic-salt-10ml', 'Strawberry Nic Salt 10ml'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: true },
  },
  {
    id: 'el-002',
    slug: 'menthol-nic-salt-10ml',
    name: 'Menthol Nic Salt 10ml',
    brand: 'Drift',
    category: 'e-liquids',
    deviceType: 'not-applicable',
    flavourFamily: 'menthol',
    nicotineStrengthMg: 20,
    vgPg: { vg: 50, pg: 50 },
    volumeMl: 10,
    priceIncVatPence: 399,
    currency: 'GBP',
    inStock: true,
    stockQty: 96,
    shortDescription: 'Cooling menthol nicotine salt e-liquid in a 10ml bottle.',
    description:
      'A cooling menthol nicotine salt e-liquid with a 50/50 VG/PG ratio for pod systems and vape pens. Supplied in a 10ml child-resistant, tamper-evident bottle.',
    specs: [
      { label: 'Volume', value: '10ml' },
      { label: 'Nicotine', value: '20mg/ml nic salt' },
      { label: 'VG/PG', value: '50/50' },
      { label: 'Flavour', value: 'Menthol' },
    ],
    images: productImages('menthol-nic-salt-10ml', 'Menthol Nic Salt 10ml'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: true },
  },
  {
    id: 'el-003',
    slug: 'vanilla-custard-50ml-shortfill',
    name: 'Vanilla Custard 50ml Shortfill',
    brand: 'Lumen',
    category: 'e-liquids',
    deviceType: 'not-applicable',
    flavourFamily: 'dessert',
    nicotineStrengthMg: 0,
    vgPg: { vg: 70, pg: 30 },
    volumeMl: 50,
    priceIncVatPence: 1099,
    currency: 'GBP',
    inStock: true,
    stockQty: 33,
    shortDescription: 'Vanilla custard shortfill, nicotine-free, in a 60ml bottle filled to 50ml.',
    description:
      'A vanilla custard flavoured shortfill e-liquid with a 70/30 VG/PG ratio, supplied nicotine-free in a 60ml bottle filled to 50ml to allow the addition of a nic shot. Suited to sub-ohm devices.',
    specs: [
      { label: 'Volume', value: '50ml in 60ml bottle' },
      { label: 'Nicotine', value: '0mg/ml (add a nic shot)' },
      { label: 'VG/PG', value: '70/30' },
      { label: 'Flavour', value: 'Vanilla custard' },
    ],
    images: productImages('vanilla-custard-50ml-shortfill', 'Vanilla Custard 50ml Shortfill'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: false },
  },
  {
    id: 'el-004',
    slug: 'mixed-berries-nic-salt-10ml',
    name: 'Mixed Berries Nic Salt 10ml',
    brand: 'Drift',
    category: 'e-liquids',
    deviceType: 'not-applicable',
    flavourFamily: 'fruit',
    nicotineStrengthMg: 6,
    vgPg: { vg: 50, pg: 50 },
    volumeMl: 10,
    priceIncVatPence: 399,
    currency: 'GBP',
    inStock: true,
    stockQty: 71,
    shortDescription: 'Mixed berries nicotine salt e-liquid in a 10ml bottle.',
    description:
      'A mixed berries nicotine salt e-liquid with a 50/50 VG/PG ratio for pod systems and vape pens. Supplied in a 10ml child-resistant, tamper-evident bottle.',
    specs: [
      { label: 'Volume', value: '10ml' },
      { label: 'Nicotine', value: '6mg/ml nic salt' },
      { label: 'VG/PG', value: '50/50' },
      { label: 'Flavour', value: 'Mixed berries' },
    ],
    images: productImages('mixed-berries-nic-salt-10ml', 'Mixed Berries Nic Salt 10ml'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: true },
  },
  {
    id: 'el-005',
    slug: 'blueberry-nic-salt-10ml',
    name: 'Blueberry Nic Salt 10ml',
    brand: 'Drift',
    category: 'e-liquids',
    deviceType: 'not-applicable',
    flavourFamily: 'fruit',
    nicotineStrengthMg: 10,
    vgPg: { vg: 50, pg: 50 },
    volumeMl: 10,
    priceIncVatPence: 399,
    currency: 'GBP',
    inStock: true,
    stockQty: 88,
    shortDescription: 'Blueberry nicotine salt e-liquid in a 10ml bottle.',
    description:
      'A blueberry nicotine salt e-liquid with a 50/50 VG/PG ratio for pod systems and vape pens. Supplied in a 10ml child-resistant, tamper-evident bottle.',
    specs: [
      { label: 'Volume', value: '10ml' },
      { label: 'Nicotine', value: '10mg/ml nic salt' },
      { label: 'VG/PG', value: '50/50' },
      { label: 'Flavour', value: 'Blueberry' },
    ],
    images: productImages('blueberry-nic-salt-10ml', 'Blueberry Nic Salt 10ml'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: true },
  },
  {
    id: 'el-006',
    slug: 'tobacco-nic-salt-10ml',
    name: 'Tobacco Nic Salt 10ml',
    brand: 'Drift',
    category: 'e-liquids',
    deviceType: 'not-applicable',
    flavourFamily: 'tobacco',
    nicotineStrengthMg: 20,
    vgPg: { vg: 50, pg: 50 },
    volumeMl: 10,
    priceIncVatPence: 399,
    currency: 'GBP',
    inStock: true,
    stockQty: 74,
    shortDescription: 'Straight tobacco nicotine salt e-liquid in a 10ml bottle.',
    description:
      'A straight tobacco nicotine salt e-liquid with a 50/50 VG/PG ratio for pod systems and vape pens. Supplied in a 10ml child-resistant, tamper-evident bottle.',
    specs: [
      { label: 'Volume', value: '10ml' },
      { label: 'Nicotine', value: '20mg/ml nic salt' },
      { label: 'VG/PG', value: '50/50' },
      { label: 'Flavour', value: 'Tobacco' },
    ],
    images: productImages('tobacco-nic-salt-10ml', 'Tobacco Nic Salt 10ml'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: true },
  },
  {
    id: 'el-007',
    slug: 'lemon-lime-nic-salt-10ml',
    name: 'Lemon Lime Nic Salt 10ml',
    brand: 'Drift',
    category: 'e-liquids',
    deviceType: 'not-applicable',
    flavourFamily: 'fruit',
    nicotineStrengthMg: 10,
    vgPg: { vg: 50, pg: 50 },
    volumeMl: 10,
    priceIncVatPence: 399,
    currency: 'GBP',
    inStock: true,
    stockQty: 65,
    shortDescription: 'Lemon and lime nicotine salt e-liquid in a 10ml bottle.',
    description:
      'A lemon and lime nicotine salt e-liquid with a 50/50 VG/PG ratio for pod systems and vape pens. Supplied in a 10ml child-resistant, tamper-evident bottle.',
    specs: [
      { label: 'Volume', value: '10ml' },
      { label: 'Nicotine', value: '10mg/ml nic salt' },
      { label: 'VG/PG', value: '50/50' },
      { label: 'Flavour', value: 'Lemon lime' },
    ],
    images: productImages('lemon-lime-nic-salt-10ml', 'Lemon Lime Nic Salt 10ml'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: true },
  },
  {
    id: 'el-008',
    slug: 'mango-ice-50ml-shortfill',
    name: 'Mango Ice 50ml Shortfill',
    brand: 'Lumen',
    category: 'e-liquids',
    deviceType: 'not-applicable',
    flavourFamily: 'fruit',
    nicotineStrengthMg: 0,
    vgPg: { vg: 70, pg: 30 },
    volumeMl: 50,
    priceIncVatPence: 1099,
    currency: 'GBP',
    inStock: true,
    stockQty: 29,
    shortDescription: 'Mango with a cooling note, nicotine-free, in a 60ml bottle filled to 50ml.',
    description:
      'A mango flavour shortfill e-liquid with a cooling note and a 70/30 VG/PG ratio, supplied nicotine-free in a 60ml bottle filled to 50ml to allow the addition of a nic shot. Suited to sub-ohm devices.',
    specs: [
      { label: 'Volume', value: '50ml in 60ml bottle' },
      { label: 'Nicotine', value: '0mg/ml (add a nic shot)' },
      { label: 'VG/PG', value: '70/30' },
      { label: 'Flavour', value: 'Mango ice' },
    ],
    images: productImages('mango-ice-50ml-shortfill', 'Mango Ice 50ml Shortfill'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: false },
  },

  // ------------------------------------------------------------- pods/coils
  {
    id: 'pc-001',
    slug: 'vaporesso-xros-replacement-pods-2-pack',
    name: 'Vaporesso XROS Replacement Pods (2-pack)',
    brand: 'Vaporesso',
    category: 'pods-coils',
    deviceType: 'coil',
    priceIncVatPence: 899,
    currency: 'GBP',
    inStock: true,
    stockQty: 64,
    shortDescription: 'Refillable 2ml replacement pods for the Vaporesso XROS series.',
    description:
      'A pack of two refillable 2ml replacement pods compatible with the Vaporesso XROS series. Mesh coil suited to nicotine salts and 50/50 e-liquids.',
    specs: [
      { label: 'Quantity', value: '2 pods' },
      { label: 'Capacity', value: '2ml refillable' },
      { label: 'Coil', value: '0.8ohm mesh' },
      { label: 'Compatibility', value: 'Vaporesso XROS series' },
    ],
    images: productImages(
      'vaporesso-xros-replacement-pods-2-pack',
      'Vaporesso XROS Replacement Pods (2-pack)',
    ),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: false },
  },
  {
    id: 'pc-002',
    slug: 'mesh-coils-0-6ohm-5-pack',
    name: 'Mesh Coils 0.6ohm (5-pack)',
    brand: 'Cobalt',
    category: 'pods-coils',
    deviceType: 'coil',
    priceIncVatPence: 1199,
    currency: 'GBP',
    inStock: true,
    stockQty: 50,
    shortDescription: 'Replacement 0.6ohm mesh coils, pack of five.',
    description:
      'A pack of five 0.6ohm mesh replacement coils for compatible sub-ohm tanks. Recommended wattage range is printed on each coil.',
    specs: [
      { label: 'Quantity', value: '5 coils' },
      { label: 'Resistance', value: '0.6ohm mesh' },
      { label: 'Type', value: 'Sub-ohm' },
    ],
    images: productImages('mesh-coils-0-6ohm-5-pack', 'Mesh Coils 0.6ohm (5-pack)'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: false },
  },
  {
    id: 'pc-003',
    slug: 'oxva-xlim-replacement-pods-3-pack',
    name: 'OXVA Xlim Replacement Pods (3-pack)',
    brand: 'OXVA',
    category: 'pods-coils',
    deviceType: 'coil',
    priceIncVatPence: 1099,
    currency: 'GBP',
    inStock: true,
    stockQty: 38,
    shortDescription: 'Refillable 2ml replacement pods for the OXVA Xlim series, pack of three.',
    description:
      'A pack of three refillable 2ml replacement pods compatible with the OXVA Xlim series. Mesh coils suit nicotine salts and 50/50 e-liquids.',
    specs: [
      { label: 'Quantity', value: '3 pods' },
      { label: 'Capacity', value: '2ml refillable' },
      { label: 'Compatibility', value: 'OXVA Xlim series' },
    ],
    images: productImages(
      'oxva-xlim-replacement-pods-3-pack',
      'OXVA Xlim Replacement Pods (3-pack)',
    ),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: false },
  },
  {
    id: 'pc-004',
    slug: 'uwell-caliburn-g4-pods-2-pack',
    name: 'Uwell Caliburn G4 Pods (2-pack)',
    brand: 'Uwell',
    category: 'pods-coils',
    deviceType: 'coil',
    priceIncVatPence: 949,
    currency: 'GBP',
    inStock: true,
    stockQty: 42,
    shortDescription: 'Refillable 2ml pods for the Uwell Caliburn G4 series, pack of two.',
    description:
      'A pack of two refillable 2ml replacement pods compatible with the Uwell Caliburn G4 series. Top-fill design with mesh coils for nicotine salts and 50/50 e-liquids.',
    specs: [
      { label: 'Quantity', value: '2 pods' },
      { label: 'Capacity', value: '2ml refillable' },
      { label: 'Compatibility', value: 'Uwell Caliburn G4 series' },
    ],
    images: productImages('uwell-caliburn-g4-pods-2-pack', 'Uwell Caliburn G4 Pods (2-pack)'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: false },
  },
  {
    id: 'pc-005',
    slug: 'aspire-flexus-af-mesh-coils-5-pack',
    name: 'Aspire Flexus AF Mesh Coils (5-pack)',
    brand: 'Aspire',
    category: 'pods-coils',
    deviceType: 'coil',
    priceIncVatPence: 1199,
    currency: 'GBP',
    inStock: true,
    stockQty: 55,
    shortDescription: 'Replacement mesh coils for Aspire Flexus devices, pack of five.',
    description:
      'A pack of five Aspire Flexus AF mesh replacement coils for compatible Flexus pod devices. Available resistances are printed on each coil.',
    specs: [
      { label: 'Quantity', value: '5 coils' },
      { label: 'Type', value: 'Mesh' },
      { label: 'Compatibility', value: 'Aspire Flexus series' },
    ],
    images: productImages(
      'aspire-flexus-af-mesh-coils-5-pack',
      'Aspire Flexus AF Mesh Coils (5-pack)',
    ),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: false },
  },

  // -------------------------------------------------------------- nic shots
  {
    id: 'ns-001',
    slug: 'nic-shot-18mg-10ml',
    name: 'Nic Shot 18mg 10ml',
    brand: 'Drift',
    category: 'nic-shots',
    deviceType: 'not-applicable',
    flavourFamily: 'unflavoured',
    nicotineStrengthMg: 18,
    vgPg: { vg: 50, pg: 50 },
    volumeMl: 10,
    priceIncVatPence: 99,
    currency: 'GBP',
    inStock: true,
    stockQty: 200,
    shortDescription: 'Unflavoured 18mg nicotine shot for use with shortfill e-liquids.',
    description:
      'An unflavoured 18mg/ml nicotine shot with a 50/50 VG/PG ratio, used to add nicotine to shortfill e-liquids. Supplied in a 10ml child-resistant, tamper-evident bottle.',
    specs: [
      { label: 'Volume', value: '10ml' },
      { label: 'Nicotine', value: '18mg/ml' },
      { label: 'VG/PG', value: '50/50' },
      { label: 'Flavour', value: 'Unflavoured' },
    ],
    images: productImages('nic-shot-18mg-10ml', 'Nic Shot 18mg 10ml'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: true },
  },
  {
    id: 'ns-002',
    slug: 'nic-shot-18mg-70vg-10ml',
    name: 'Nic Shot 18mg 70VG 10ml',
    brand: 'Lumen',
    category: 'nic-shots',
    deviceType: 'not-applicable',
    flavourFamily: 'unflavoured',
    nicotineStrengthMg: 18,
    vgPg: { vg: 70, pg: 30 },
    volumeMl: 10,
    priceIncVatPence: 99,
    currency: 'GBP',
    inStock: true,
    stockQty: 180,
    shortDescription: 'Unflavoured 18mg high-VG nicotine shot for sub-ohm shortfills.',
    description:
      'An unflavoured 18mg/ml nicotine shot with a 70/30 VG/PG ratio, intended for adding nicotine to high-VG shortfill e-liquids. Supplied in a 10ml child-resistant, tamper-evident bottle.',
    specs: [
      { label: 'Volume', value: '10ml' },
      { label: 'Nicotine', value: '18mg/ml' },
      { label: 'VG/PG', value: '70/30' },
      { label: 'Flavour', value: 'Unflavoured' },
    ],
    images: productImages('nic-shot-18mg-70vg-10ml', 'Nic Shot 18mg 70VG 10ml'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: true },
  },
  {
    id: 'ns-003',
    slug: 'nic-shot-salt-20mg-10ml',
    name: 'Nic Salt Shot 20mg 10ml',
    brand: 'Drift',
    category: 'nic-shots',
    deviceType: 'not-applicable',
    flavourFamily: 'unflavoured',
    nicotineStrengthMg: 20,
    vgPg: { vg: 50, pg: 50 },
    volumeMl: 10,
    priceIncVatPence: 99,
    currency: 'GBP',
    inStock: true,
    stockQty: 140,
    shortDescription: 'Unflavoured 20mg nicotine salt shot for shortfill e-liquids.',
    description:
      'An unflavoured 20mg/ml nicotine salt shot with a 50/50 VG/PG ratio, used to add nicotine to shortfill e-liquids. Supplied in a 10ml child-resistant, tamper-evident bottle.',
    specs: [
      { label: 'Volume', value: '10ml' },
      { label: 'Nicotine', value: '20mg/ml nic salt' },
      { label: 'VG/PG', value: '50/50' },
      { label: 'Flavour', value: 'Unflavoured' },
    ],
    images: productImages('nic-shot-salt-20mg-10ml', 'Nic Salt Shot 20mg 10ml'),
    compliance: { mhraNotified: true, singleUseDisposable: false, containsNicotine: true },
  },

  // ------------------------------------------------------------ accessories
  {
    id: 'ac-001',
    slug: 'usb-c-charging-cable',
    name: 'USB-C Charging Cable',
    brand: 'Meridian',
    category: 'accessories',
    deviceType: 'not-applicable',
    priceIncVatPence: 499,
    currency: 'GBP',
    inStock: true,
    stockQty: 88,
    shortDescription: 'USB-C charging cable for compatible devices.',
    description:
      'A 0.5m USB-C charging cable for compatible pod systems, vape pens and mods. Data and charge.',
    specs: [
      { label: 'Length', value: '0.5m' },
      { label: 'Connector', value: 'USB-A to USB-C' },
    ],
    images: productImages('usb-c-charging-cable', 'USB-C Charging Cable'),
    compliance: { mhraNotified: false, singleUseDisposable: false, containsNicotine: false },
  },
  {
    id: 'ac-002',
    slug: '18650-battery-charger',
    name: '18650 Battery Charger',
    brand: 'Cobalt',
    category: 'accessories',
    deviceType: 'not-applicable',
    priceIncVatPence: 1499,
    currency: 'GBP',
    inStock: true,
    stockQty: 25,
    shortDescription: 'Dual-bay charger for 18650 batteries.',
    description:
      'A dual-bay charger for 18650 removable batteries, with overcharge protection and a USB-C input. Batteries not included.',
    specs: [
      { label: 'Bays', value: '2' },
      { label: 'Input', value: 'USB-C' },
      { label: 'Protection', value: 'Overcharge cut-off' },
    ],
    images: productImages('18650-battery-charger', '18650 Battery Charger'),
    compliance: { mhraNotified: false, singleUseDisposable: false, containsNicotine: false },
  },
  {
    id: 'ac-003',
    slug: 'usb-c-charging-cable-1m',
    name: 'USB-C Charging Cable 1m',
    brand: 'Meridian',
    category: 'accessories',
    deviceType: 'not-applicable',
    priceIncVatPence: 599,
    currency: 'GBP',
    inStock: true,
    stockQty: 72,
    shortDescription: '1m USB-C charging cable for compatible devices.',
    description:
      'A 1m USB-C charging cable for compatible pod systems, vape pens and mods. Data and charge.',
    specs: [
      { label: 'Length', value: '1m' },
      { label: 'Connector', value: 'USB-A to USB-C' },
    ],
    images: productImages('usb-c-charging-cable-1m', 'USB-C Charging Cable 1m'),
    compliance: { mhraNotified: false, singleUseDisposable: false, containsNicotine: false },
  },
]
